### ISSUE TITLE
a problem of coleman index

### ISSUE THREAD

**Issue by letitbk** [mbojan/netseg#13]
Hi, thanks for making this useful package. When I use this `coleman` to calculate the Coleman index, I realize that this package does not produce the right number.  In Coleman's original paper: https://meridian.allenpress.com/human-organization/article-abstract/17/4/28/69903/Relational-Analysis-The-Study-of-Social, you can found an example.

<img width="374" alt="image" src="https://user-images.githubusercontent.com/18311784/191496431-3777f8ec-5c18-4bb7-b70f-878c4312ccbb.png">

Here Coleman calculated the coleman's index:
<img width="202" alt="image" src="https://user-images.githubusercontent.com/18311784/191496527-67be0631-127d-4db9-90d1-adf95ed77564.png">

However, negseg::coleman generates the wrong number. here's a comparison.

```
m = matrix(c(45,15,20,20), byrow=TRUE, nrow=2)
gsizes = c(60,40)
coleman(m, gsizes)
[1] 0.38125 0.17500
```

FYI, my own calculation is like this:
```
coleman_correct = function(m, gsizes){
	coleman_IH = unlist(lapply(seq_along(gsizes), function(i){
			si = m[i, i] / gsizes[i]
			ti = sum(m[i, ]) / gsizes[i]
			wi = gsizes[i] / sum(gsizes)
			IH = (si/ti - wi) / (1 - wi)
			return(IH)
		}))
	return(coleman_IH)
}
coleman_correct(m, gsizes)
[1] 0.3750000 0.1666667
```

**Comment by mbojan** [comment]
Hi @letitbk . The package calculation is correct because in the paper James Coleman uses approximation to calculate the expected number of group ties. See:

https://github.com/mbojan/netseg/blob/8373835bf41a6bbda83253ba852a55fd7aa26df3/tests/testthat/test-coleman.R#L22-L24

and the associated test.

**Comment by letitbk** [comment]
Thanks for your explanation. Yes, that makes sense. I carefully read Coleman's paper, and realize that Coleman proposed two different indexes depending on whether the actual number of within group ties is larger or smaller than the expected number of within group ties. I think that it might be more useful if this function allows us to choose which index we can use. For example, the current `coleman` function always produce -1 if the diagnal value is 0, and there's a big jump when the diagonal value becomes 1.  Here's an example. This problem gets worse when the number of groups is large.
```
> m1 = matrix(c(0,3,20,20), byrow=TRUE, nrow=2)
> m2 = matrix(c(1,3,20,20), byrow=TRUE, nrow=2)
> gsizes = c(60,40)
> coleman(m1, gsizes)
[1] -1.000  0.175
> coleman(m2, gsizes)
[1] -0.5805085  0.1750000
```
So, I would propose something like this. 

```
#' @rdname coleman
#' @param gsizes numeric vector of group sizes
#' @param loops logical, whether loops are allowed
#' @param tie "formation", "dissolution", "both", the default is "both"
#' @export
coleman.table <- function(object, gsizes=NULL, loops=FALSE, tie = "both", ...)
{
  dims <- dim(object)
  # only contact layer
  if( length(dims) == 2 )
  {
    stopifnot( !is.null(gsizes) )
    m <- object
  } else
  {
    stopifnot( length(dims) == 3 )
    gsizes <- group_sizes(object, directed=TRUE, loops=loops)
    m <- object[,,2]
  }
  # take group sizes
  degsums <- rowSums(m)
  # expected number of within-group ties for each group
  ewg <- degsums * (gsizes - 1) / (sum(gsizes) - 1)
  # rval
  r <- (diag(m) - ewg) / (degsums - ewg)
  i <- diag(m) <= ewg
  repl <- (diag(m) - ewg) / ewg
  if (tie == "formation") {
   y <- r 
  } else if (tie == "dissolution") {
   y <- repl
  } else if (tie == "both") {
    y <- r 
    y[i] <- repl[i]
  } 
  
  structure(as.numeric(y), names=names(gsizes))
}
```

**Comment by mbojan** [comment]
I believe Coleman's intention was not to propose two indices but rather clearly derive the final one varying from -1 to +1. It is not clear to me why would you want to ever use only "half" of the index as you suggest (why the labels "formation" and "dissolution"?). Moreover, I the modification you suggest does not address the problem:

> For example, the current `coleman` function always produce -1 if the diagnal value is 0, and there's a big jump when the diagonal value becomes 1. Here's an example. This problem gets worse when the number of groups is large.

... as with your function you get:

```
> f(m1, gsizes, tie = "both")
[1] -1.000  0.175
> f(m2, gsizes, tie = "both")
[1] -0.5805085  0.1750000
> f(m1, gsizes, tie = "formation")
[1] -1.475  0.175
> f(m2, gsizes, tie = "formation")
[1] -0.85625  0.17500
> f(m1, gsizes, tie = "dissolution")
[1] -1.0000000  0.2692308
> f(m2, gsizes, tie = "dissolution")
[1] -0.5805085  0.2692308
```

so still a jump irrespectively of the `tie`.
