### ISSUE TITLE
Symmetrize

### ISSUE THREAD

**Issue by krisher1** [mbojan/netseg#14]
The "upper" and "lower" options for the `symmetrize()` function don't quite work as expected (see attached "symmetrized" matrix). Right now the function for upper is:

`rval[lower.tri(mat)] <- mat[upper.tri(mat)]`

The following would correct this:

`rval[lower.tri(mat)] <- t(mat)[lower.tri(mat)]`

Thanks for the helpful package!
![Screenshot 2023-02-23 at 3 06 45 PM](https://user-images.githubusercontent.com/7857718/221018485-c8411245-c438-4a1d-b008-dafcf60775b8.png)

**Comment by mbojan** [comment]
Thanks @krisher1 for reporting. Wow, oops... hard to believe that one has gone under the radar.
