### ISSUE TITLE
Test failures with the development version of igraph

### ISSUE THREAD

**Issue by krlmlr** [mbojan/netseg#16]
We're changing the layout of igraph objects. This leads to check failures in your package, see https://github.com/igraph/rigraph/blob/f-igraph-t-idx-revdepcheck/revdep/problems.md and https://github.com/igraph/rigraph/pull/789 for details.

To reproduce, please install the development version of igraph via

```r
# install.packages("pak")
pak::pak("igraph/rigraph")
```

and run `R CMD check` on your package.

We plan to release an igraph update on June 12, three weeks from now. Can you please send an update to CRAN that fixes the checks, or tell me that the failure is unexpected and we should be fixing this?

Specifically, the following code now fails:

``` r
options(conflicts.policy = list(warn = FALSE))
library(netseg)
ssi(EF3, "race")
#> Error in igraph::induced.subgraph(g, which(ids == b)): At core/core/vector.pmt:1030 : Assertion failed: v->stor_begin != NULL. This is an unexpected igraph error; please report this as a bug, along with the steps to reproduce it.
#> Please restart your R session to avoid crashes or other surprising behavior.
```

<sup>Created on 2023-05-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This is probably us, but I'm having a hard time figuring out what's happening here. Thank you for your help!

**Comment by mbojan** [comment]
Thanks. I'll look into it.

**Comment by krlmlr** [comment]
Thanks. I just merged an igraph PR that may be necessary to replicate the issue.

**Comment by mbojan** [comment]
I can replicate it and it is very strange. I think it is **igraph** bug because it is `igraph::subgraph()` tripping on an igraph object, of which there is nothing out of the ordinary as far as i can tell. Will poke some more though.

**Comment by mbojan** [comment]
@krlmlr, and so it is in igraph, here is a way to replicate it. I'm not sure why it is breaking:

```r
g <- make_lattice(c(5, 6))
gg <- as.directed(g, mode = "mutual")
V(gg)$id <- V(g)
degs <- igraph::degree(gg, mode="out")
for(i in seq(1, igraph::vcount(gg)))
  E(gg)[.from(i)]$weight <- 1/degs[i]
subgraph(gg, 1)
```

**Comment by krlmlr** [comment]
Thanks, this is useful! We can work with that, no further action needed for now.

**Comment by mbojan** [comment]
That's actually a good nudge to simplify that part in 'netseg' because I don't need the whole vertex sequence as the attribute, just the ids.

**Comment by krlmlr** [comment]
Yeah, I wonder where this usage pattern comes from.

**Comment by mbojan** [comment]
I need to compute on various subgraphs of the mastergraph and assign the results to the nodes in the master graph. It seemed cognitively easiest to store the IDs so that they are accessible when working with a subgraph. This was written 2009-ish originally too :)

**Comment by krlmlr** [comment]
Storing the IDs is fine, but storing them as raw numbers perhaps also works.

igraph/rigraph#808 fixes this problem, this will probably land soon, also on CRAN.

**Comment by mbojan** [comment]
By [5eab08f](https://github.com/mbojan/netseg/commit/5eab08f359673e9f82f980cf5c52f950f4a0767e) resorting to integer IDs, preemptively.
